// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt1ZSOSkncud44iWXVgOmqBFd8yzG9e2Y',
    appId: '1:392405607881:web:fc43b939cb6ba319963418',
    messagingSenderId: '392405607881',
    projectId: 'lingowise-8dde2',
    authDomain: 'lingowise-8dde2.firebaseapp.com',
    storageBucket: 'lingowise-8dde2.firebasestorage.app',
    measurementId: 'G-CJS44FQJTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW4pSQeozfwvVkFUibnbgGtPWpMBwSHcc',
    appId: '1:392405607881:android:cf3deafae72a5e4b963418',
    messagingSenderId: '392405607881',
    projectId: 'lingowise-8dde2',
    storageBucket: 'lingowise-8dde2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRfE_Rhnkc0sTxY48xFtK-Va_pTZc8HME',
    appId: '1:392405607881:ios:ec8f14950f190dd6963418',
    messagingSenderId: '392405607881',
    projectId: 'lingowise-8dde2',
    storageBucket: 'lingowise-8dde2.firebasestorage.app',
    iosBundleId: 'org.agaafar.lingowise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRfE_Rhnkc0sTxY48xFtK-Va_pTZc8HME',
    appId: '1:392405607881:ios:ec8f14950f190dd6963418',
    messagingSenderId: '392405607881',
    projectId: 'lingowise-8dde2',
    storageBucket: 'lingowise-8dde2.firebasestorage.app',
    iosBundleId: 'org.agaafar.lingowise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt1ZSOSkncud44iWXVgOmqBFd8yzG9e2Y',
    appId: '1:392405607881:web:7f23db159dafc75d963418',
    messagingSenderId: '392405607881',
    projectId: 'lingowise-8dde2',
    authDomain: 'lingowise-8dde2.firebaseapp.com',
    storageBucket: 'lingowise-8dde2.firebasestorage.app',
    measurementId: 'G-NER7KNC8KY',
  );
}
